

    // businessman: "businessperson",
    // businesswoman: "businessperson",
    // draught: "draft", // on list
    // labell: "label",
    // travell: "travel",
    // vet: "veterinarian",
    ad: "advertisement",
    advisor: "adviser",
    aeroplan: "airplane",
    ageing: "aging",
    aluminum: "aluminium", // i.e. the 'british' is standard
    analytic: "analytical",
    appal: "appall",
    archeology: "archaeology",
    artefact: "artifact",
    auntie: "aunt",
    aunty: "aunt",
    axe: "ax",
    bacterium: "bacteria",
    barbq: "barbecue",
    bbq: "barbecue",
    blond: "blonde",
    bookshop: "bookstore",
    botanic: "botanical",
    cab: "taxi",
    carer: "caretaker",
    carryout: "takeaway",
    catalogu: "catalog",
    catsup: "ketchup",
    centigrade: "celsius",
    chairman: "chair",
    chairwoman: "chair",
    chequ: "check",
    chequebook: "checkbook",
    chili: "chilli",
    cosy: "cozy",
    councillor: "councilor",
    counsellor: "counselor",
    crosswalk: "crossing",
    datum: "data",
    dependant: "dependent",
    despatch: "dispatch",
    disc: "disk",
    distil: "distill",
    donut: "doughnut",
    dorm: "dormitory",
    enquir: "inquire / inquiry",
    enrol: "enroll",
    fulfill: "fulfil",
    gaol: "jail",
    gramm: "gram",
    grey: "gray",
    groom: "bridegroom",
    guerilla: "guerrilla",
    gull: "seagull",
    homogenous: "homogeneous",
    icebox: "refrigerator",
    instalment: "installment",
    jewelry: "jewellery",
    judgement: "judgment",
    kitty: "kitten",
    lab: "laboratory",
    ladybird: "ladybug",
    limo: "limousine",
    litchi: "lychee",
    mailman: "mail carrier",
    mamma: "mother",
    manoeuvr: "maneuver", // include because contains oe>e AND re>er
    mom: "mother",
    momma: "mother",
    mommy: "mother",
    mould: "mold",
    mum: "mother",
    mummy: "mother",
    nope: "no",
    orientat: "orient",
    pingpong: "table tennis",
    plough: "plow",
    postman: "mail carrier",
    programme: "program",
    providing: "provided",
    pyjama: "pajama",
    quartette: "quartet",
    railway: "railroad",
    rhino: "rhinoceros",
    rotatory: "rotary",
    sceptical: "skeptical",
    skilful: "skillful",
    sledge: "sled",
    soya: "soy",
    soyabean: "soybean",
    spaceship: "spacecraft",
    specialit: "specialty",
    streetcar: "trolley",
    sulphur: "sulfur",
    symbolical: "symbolic",
    takeout: "takeaway",
    taxicab: "taxi",
    tb: "tuberculosis",
    teeshirt: "t-shirt",
    tram: "trolley",
    tramcar: "trolley",
    tshirt: "t-shirt",
    tummy: "stomach",
    tyre: "tire",
    vet: "veteran / veterinarian",
    vs: "versus",
    whisky: "whiskey",
    xmas: "christmas",
    yoghurt: "yogurt",