awlHi =[
  ["abstract", 6, ["abstraction", "abstractly"]],
["accurate", 6, ["accuracy", "accurately", "inaccuracy", "inaccurate"]],
["acknowledge", 6, ["acknowledged", "acknowledgement"]],
["aggregate", 6, ["aggregated", "aggregation"]],
["allocate", 6, ["allocated", "allocation"]],
["assign", 6, ["assigned", "assignment", "reassign", "reassigned", "unassigned"]],
["attach", 6, ["attached", "attachment", "unattached"]],
["author", 6, ["authored", "authorship"]],
["bond", 6, ["bonded"]],
["brief", 6, ["brevity", "briefed", "briefly"]],
["capable", 6, ["capability", "incapable"]],
["cite", 6, ["citation", "cited"]],
["cooperate", 6, ["co-operate", "co-operated", "co-operates", "co-operation", "co-operative", "co-operatively", "cooperated", "cooperation", "cooperative", "cooperatively"]],
["discriminate", 6, ["discriminated", "discrimination"]],
["display", 6, ["displayed"]],
["diverse", 6, ["diversely", "diversification", "diversified", "diversify", "diversity"]],
["domain", 6, []],
["edit", 6, ["edited", "edition", "editor", "editorial"]],
["enhance", 6, ["enhanced", "enhancement"]],
["estate", 6, []],
["exceed", 6, ["exceeded"]],
["expert", 6, ["expertise", "expertly"]],
["explicit", 6, ["explicitly"]],
["federal", 6, ["federation"]],
["fee", 6, []],
["flexible", 6, ["flexibility", "inflexibility", "inflexible"]],
["furthermore", 6, []],
["gender", 6, []],
["ignorant", 6, ["ignorance", "ignore", "ignored"]],
["incentive", 6, []],
["incidence", 6, ["incident", "incidentally"]],
["incorporate", 6, ["incorporated", "incorporation"]],
["index", 6, ["indexed"]],
["inhibit", 6, ["inhibited", "inhibition"]],
["initiate", 6, ["initiated", "initiation", "initiative", "initiator"]],
["input", 6, []],
["instruct", 6, ["instructed", "instruction", "instructive", "instructor"]],
["intelligent", 6, ["intelligence", "intelligently", "unintelligent"]],
["interval", 6, []],
["lecture", 6, ["lectured", "lecturer"]],
["migrate", 6, ["migrant", "migrated", "migration", "migratory"]],
["minimum", 6, []],
["ministry", 6, ["ministered", "ministerial"]],
["motive", 6, ["motivate", "motivated", "motivation", "unmotivated"]],
["neutral", 6, ["neutralisation", "neutrality", "neutralization", "neutralize", "neutralized"]],
["nevertheless", 6, []],
["overseas", 6, []],
["precede", 6, ["preceded", "precedence", "precedent", "unprecedented"]],
["presume", 6, ["presumably", "presumed", "presumption"]],
["rational", 6, ["irrational", "rationalisation", "rationalism", "rationality", "rationalization", "rationalize", "rationalized", "rationally"]],
["recover", 6, ["recoverable", "recovered", "recovery"]],
["reveal", 6, ["revealed", "revelation"]],
["scope", 6, []],
["subsidy", 6, ["subsidiary", "subsidize", "subsidized"]],
["tape", 6, ["taped"]],
["trace", 6, ["traceable", "traced"]],
["transform", 6, ["transformation", "transformed"]],
["transport", 6, ["transportation", "transported", "transporter"]],
["underlie", 6, ["underlay"]],
["utilize", 6, ["utilisation", "utilizer", "utility", "utilization", "utilize", "utilized"]],
["adapt", 7, ["adaptability", "adaptable", "adaptation", "adapted", "adaptive"]],
["adult", 7, ["adulthood"]],
["advocate", 7, ["advocacy", "advocated"]],
["aid", 7, ["aided", "unaided"]],
["channel", 7, ["channelled"]],
["chemical", 7, ["chemically"]],
["classic", 7, ["classical"]],
["comprehensive", 7, ["comprehensively"]],
["comprise", 7, ["comprised"]],
["confirm", 7, ["confirmation", "confirmed"]],
["contrary", 7, ["contrarily"]],
["convert", 7, ["conversion", "converted", "convertible"]],
["couple", 7, ["coupled"]],
["decade", 7, []],
["definite", 7, ["definitely", "definitive", "indefinite", "indefinitely"]],
["deny", 7, ["deniable", "denial", "denied", "undeniable"]],
["differentiate", 7, ["differentiated", "differentiation"]],
["dispose", 7, ["disposable", "disposal", "disposed"]],
["dynamic", 7, ["dynamically"]],
["eliminate", 7, ["eliminated", "elimination"]],
["empirical", 7, ["empirically", "empiricism"]],
["equip", 7, ["equipment", "equipped"]],
["extract", 7, ["extracted", "extraction"]],
["file", 7, ["filed"]],
["finite", 7, ["infinite", "infinitely"]],
["foundation", 7, []],
["globe", 7, ["global", "globalisation", "globalization", "globally"]],
["grade", 7, ["graded"]],
["guarantee", 7, ["guaranteed"]],
["hierarchy", 7, ["hierarchical"]],
["identical", 7, ["identically"]],
["ideology", 7, ["ideological", "ideologically"]],
["infer", 7, ["inference", "inferred"]],
["innovate", 7, ["innovated", "innovation", "innovative", "innovator"]],
["insert", 7, ["inserted", "insertion"]],
["intervene", 7, ["intervened", "intervention"]],
["isolate", 7, ["isolated", "isolation", "isolationism"]],
["media", 7, []],
["mode", 7, []],
["paradigm", 7, []],
["phenomenon", 7, ["phenomena", "phenomenal"]],
["priority", 7, ["prioritisation", "prioritization", "prioritize", "prioritized"]],
["prohibit", 7, ["prohibited", "prohibition", "prohibitive"]],
["publication", 7, []],
["quote", 7, ["quotation", "quoted"]],
["release", 7, ["released"]],
["reverse", 7, ["irreversible", "reversal", "reversed", "reversible"]],
["simulate", 7, ["simulated", "simulation"]],
["sole", 7, ["solely"]],
["somewhat", 7, []],
["submit", 7, ["submission", "submitted"]],
["successor", 7, ["succession", "successive", "successively"]],
["survive", 7, ["survival", "survived", "survivor"]],
["thesis", 7, []],
["topic", 7, ["topical"]],
["transmit", 7, ["transmission", "transmitted"]],
["ultimate", 7, ["ultimately"]],
["unique", 7, ["uniquely"]],
["visible", 7, ["invisibility", "invisible", "visibility", "visibly"]],
["voluntary", 7, ["voluntarily", "volunteer", "volunteered"]],
["abandon", 8, ["abandoned", "abandonment"]],
["accompany", 8, ["accompanied", "accompaniment", "unaccompanied"]],
["accumulate", 8, ["accumulated", "accumulation"]],
["ambiguous", 8, ["ambiguity", "unambiguously"]],
["append", 8, ["appended", "appendix"]],
["appreciate", 8, ["appreciable", "appreciably", "appreciated", "appreciation", "unappreciated"]],
["arbitrary", 8, ["arbitrarily"]],
["automate", 8, ["automated", "automatic", "automatically", "automation"]],
["bias", 8, ["biased", "unbiased"]],
["chart", 8, ["charted", "uncharted"]],
["clarify", 8, ["clarification", "clarified", "clarity"]],
["commodity", 8, []],
["complement", 8, ["complementary", "complemented"]],
["conform", 8, ["conformability", "conformable", "conformance", "conformation", "conformed", "conformist", "conformity", "non-conformist", "non-conformists", "non-conformity", "nonconformist", "nonconformity"]],
["contemporary", 8, []],
["contradict", 8, ["contradicted", "contradiction", "contradictory"]],
["crucial", 8, ["crucially"]],
["currency", 8, []],
["denote", 8, ["denotation", "denoted"]],
["detect", 8, ["detectable", "detected", "detection", "detective", "detector"]],
["deviate", 8, ["deviated", "deviation"]],
["displace", 8, ["displaced", "displacement"]],
["drama", 8 ["dramatic", "dramatically", "dramatisation", "dramatist", "dramatization", "dramatize", "dramatized"]],
["eventual", 8, ["eventuality", "eventually"]],
["exhibit", 8, ["exhibited", "exhibition"]],
["exploit", 8, ["exploitation", "exploited"]],
["fluctuate", 8, ["fluctuated", "fluctuation"]],
["guideline", 8, []],
["highlight", 8, ["highlighted"]],
["implicit", 8, ["implicitly"]],
["induce", 8, ["induced", "induction"]],
["inevitable", 8, ["inevitability", "inevitably"]],
["infrastructure", 8, []],
["inspect", 8, ["inspected", "inspection", "inspector"]],
["intense", 8, ["intensely", "intensification", "intensified", "intensify", "intension", "intensity", "intensive", "intensively"]],
["manipulate", 8, ["manipulated", "manipulation", "manipulative"]],
["minimize", 8, ["minimize", "minimized"]],
["nuclear", 8, []],
["offset", 8, []],
["paragraph", 8, []],
["plus", 8, []],
["practitioner", 8, []],
["predominant", 8, ["predominance", "predominantly", "predominate", "predominated"]],
["prospect", 8, ["prospective"]],
["radical", 8, ["radically"]],
["random", 8, ["randomly"]],
["reinforce", 8, ["reinforced", "reinforcement"]],
["restore", 8, ["restoration", "restored"]],
["revise", 8, ["revised", "revision"]],
["schedule", 8, ["reschedule", "rescheduled", "scheduled", "unscheduled"]],
["tense", 8, ["tensely", "tenser", "tensest", "tension"]],
["terminate", 8, ["terminal", "terminated", "termination"]],
["theme", 8, ["thematic", "thematically"]],
["thereby", 8, []],
["uniform", 8, ["uniformity", "uniformly"]],
["vehicle", 8, []],
["via", 8, []],
["virtual", 8, ["virtually"]],
["visual", 8, ["visualisation", "visualization", "visualize", "visualized", "visually"]],
["widespread", 8, []],
["accommodate", 9, ["accommodated", "accommodation"]],
["analogy", 9, []],
["anticipate", 9, ["anticipated", "anticipation", "unanticipated"]],
["assure", 9, ["assurance", "assured", "assuredly"]],
["attain", 9, ["attainable", "attained", "attainment", "unattainable"]],
["behalf", 9, []],
["bulk", 9, ["bulky"]],
["cease", 9, ["ceased"]],
["coherent", 9, ["coherence", "coherently", "incoherent", "incoherently"]],
["coincide", 9, ["coincided", "coincidence", "coincident", "coincidental"]],
["commence", 9, ["commenced", "commencement", "recommenced"]],
["compatible", 9, ["compatibility", "incompatibility", "incompatible"]],
["concurrent", 9, ["concurrently"]],
["confine", 9, ["confined", "unconfined"]],
["controversy", 9, ["controversial", "controversially", "uncontroversial"]],
["converse", 9, ["conversely"]],
["device", 9, []],
["devote", 9, ["devoted", "devotedly", "devotion"]],
["diminish", 9, ["diminished", "diminution", "undiminished"]],
["distort", 9, ["distorted", "distortion"]],
["duration", 9, []],
["erode", 9, ["eroded", "erosion"]],
["ethic", 9, ["ethical", "ethically", "unethical"]],
["format", 9, ["formatted"]],
["found", 9, ["founded", "founder", "unfounded"]],
["inherent", 9, ["inherently"]],
["insight", 9, ["insightful"]],
["integral", 9, []],
["intermediate", 9, []],
["manual", 9, ["manually"]],
["mature", 9, ["immature", "immaturity", "maturation", "maturational", "matured", "maturity"]],
["mediate", 9, ["mediated", "mediation"]],
["medium", 9, []],
["military", 9, []],
["minimal", 9, ["minimalisation", "minimalist", "minimalistic", "minimalization", "minimalize", "minimalized", "minimally"]],
["mutual", 9, ["mutually"]],
["norm", 9, []],
["overlap", 9, ["overlapped"]],
["passive", 9, ["passively", "passivity"]],
["portion", 9, []],
["preliminary", 9, []],
["protocol", 9, []],
["qualitative", 9, ["qualitatively"]],
["refine", 9, ["refined", "refinement"]],
["relax", 9, ["relaxation", "relaxed"]],
["restrain", 9, ["restrained", "restraint", "unrestrained"]],
["revolution", 9, ["revolutionary", "revolutionist", "revolutionize", "revolutionized"]],
["rigid", 9, ["rigidity", "rigidly"]],
["route", 9, ["routed"]],
["scenario", 9, []],
["sphere", 9, ["spherical", "spherically"]],
["subordinate", 9, ["subordination"]],
["supplement", 9, ["supplementary", "supplemented"]],
["suspend", 9, ["suspended", "suspension"]],
["team", 9, ["teamed"]],
["temporary", 9, ["temporarily"]],
["trigger", 9, ["triggered"]],
["unify", 9, ["unification", "unified"]],
["violate", 9, ["violated", "violation"]],
["vision", 9, []],
["adjacent", 10, []],
["albeit", 10, []],
["assemble", 10, ["assembled", "assembly"]],
["collapse", 10, ["collapsed", "collapsible"]],
["colleague", 10, []],
["compile", 10, ["compilation", "compiled"]],
["conceive", 10, ["conceivable", "conceivably", "conceived", "inconceivable", "inconceivably"]],
["convince", 10, ["convinced", "convincingly", "unconvinced"]],
["depress", 10, ["depressed", "depression"]],
["encounter", 10, ["encountered"]],
["enormous", 10, ["enormity", "enormously"]],
["forthcoming", 10, []],
["incline", 10, ["inclination", "inclined"]],
["integrity", 10, []],
["intrinsic", 10, ["intrinsically"]],
["invoke", 10, ["invoked"]],
["levy", 10, []],
["likewise", 10, []],
["nonetheless", 10, []],
["notwithstanding", 10, []],
["odd", 10, []],
["ongoing", 10, []],
["panel", 10, ["panelled"]],
["persist", 10, ["persisted", "persistence", "persistent", "persistently"]],
["pose", 10, ["posed"]],
["reluctance", 10, ["reluctant", "reluctantly"]],
["so-called", 10, []],
["straightforward", 10, []],
["undergo", 10, ["undergone", "underwent"]],
["whereby", 10, []]
]
